### ISSUE TITLE
`-q` is not working.

### ISSUE THREAD

**Issue by HRD-Ryo** [RogerLab/meow#5]
`-q` is not working. It seems to be fixed at 0.75.
See the attached files. `esmodel.nex` generated under different `-q` values are identical.

```
$ diff test_q03_esmodel.nex.txt test_q075_esmodel.nex.txt 
2c2
< 2024-10-10 17:57:46.675959     Execution time: 00:00:23
---
> 2024-10-10 17:57:00.44898     Execution time: 00:00:23
8c8
<  Quantile:  0.3 	Cluster type:  hclust 	Penalty:  1e-10 
---
>  Quantile:  0.75 	Cluster type:  hclust 	Penalty:  1e-10 
```

[test_q03_esmodel.nex.txt](https://github.com/user-attachments/files/17334142/test_q03_esmodel.nex.txt)
[test_q075_esmodel.nex.txt](https://github.com/user-attachments/files/17334143/test_q075_esmodel.nex.txt)

**Comment by HectorBanos** [comment]
More exploration is needed since  for me and my data sets it is working

**Comment by HectorBanos** [comment]
We discovered it was only affecting Entropy and K. it has now fixed
